### ISSUE TITLE
Finalize Plan_Of_Action.md

### ISSUE THREAD

**Issue by maharshi-gg** [pranav2595/American-Football-Analytics-Application#18]

**Comment by maharshi-gg** [comment]
@yash97 @pranav2595 @pururaj1908 @yoonchulro - please check whether there are any changes to the Plan_Of_Action.md: If not so, then please comment here to vote to close this issue.

**Comment by pranav2595** [comment]
We have enough plan updated in the canban board so I vote to close this issue.
